name: hello_world
author: valory
version: 0.1.0
description: A simple demonstration of a simple ABCI application
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiapubcoersqnsnh3acia5hd7otzt7kjxekr6gkbrlumv6tkajl6jm
fingerprint_ignore_patterns: []
agent: valory/hello_world:0.1.0:bafybeihajr3rtkofmxx45cozagz5g3yizwydzio3vq4bo74num3zphpdm4
number_of_agents: 4
---
public_id: valory/hello_world_abci:0.1.0
type: skill
models:
  params:
    args:
      service_registry_address: null
      share_tm_config_on_startup: false
      on_chain_service_id: null
      setup:
        all_participants:
        - - '0x0000000000000000000000000000000000000000'
        safe_contract_address:
        - '0x0000000000000000000000000000000000000000'
        consensus_threshold:
        - null
      hello_world_message: ${HELLO_WORLD_STRING:str:HELLO_WORLD!}
  benchmark_tool:
    args:
      log_dir: /benchmarks
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${SERVICE_HELLO_WORLD_RPC:str:http://host.docker.internal:8545}
      chain_id: 31337
      poa_chain: false
      default_gas_price_strategy: eip1559
