name: simple_abci
author: valory
version: 0.1.0
description: A simple demonstration of a simple ABCI application
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeia3zelg4urfp2g4srt6p3prza5et2hcwk57gsntiabut6ljs6yihe
fingerprint_ignore_patterns: []
agent: valory/simple_abci:0.1.0:bafybeiclpghve4sq5y5uwkkfzyafvzqro57viqrqlg46gzkw6knvlv5cgy
number_of_agents: 4
---
extra:
  benchmark_persistence_params:
    args: &id001
      log_dir: /benchmarks
override_type: multiple
public_id: valory/simple_abci:0.1.0
type: skill
0:
  models:
    benchmark_tool:
      args: *id001
1:
  models:
    benchmark_tool:
      args: *id001
2:
  models:
    benchmark_tool:
      args: *id001
3:
  models:
    benchmark_tool:
      args: *id001
