agent_name: test_abci
author: valory
version: 0.1.0
license: Apache-2.0
description: Agent for testing the ABCI connection.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeib2s5p42rb4mbn7ag4jmjwutcm2mhvhb7q7vekxevr565crxkk6zy
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:bafybeibijiymtljtntnoiulpymqkcwdt7h3u2q7sufzuuq3y4xb6xq6rli
- valory/http_client:0.1.0:bafybeihxn5si5ryng6n3u2nzd4l67lvtzq4cyvkfxacdf4ctai3okwueq4
- valory/ledger:0.1.0:bafybeicany7u4gcxkciut26big7iytat4uu2krnjy2fmvagiykr35zqy3e
- valory/p2p_libp2p_client:0.1.0:bafybeigvayl4ykzqf6o6bw2irv7am3qvczjoeu7yjhzn27ajiwvcio3lxm
contracts: []
protocols:
- open_aea/signing:1.0.0:bafybeid6f5ceool4evgaxdegs5pkjoivqjk3mo3ehctalswngb5m5c32wm
- valory/abci:0.1.0:bafybeig5q4s2neusopb3opvdzmu7o6owmx2a2pcnbeobrkwkvoazf6nh7e
- valory/contract_api:1.0.0:bafybeiabywvaxwk5k3vjqa7wf7asajrjna2mwio3lo3cwxohe46fvyjmxq
- valory/http:1.0.0:bafybeihoavujwpal63dwwwigpsy74oerrblyzxllsbdoz7slx45pm326yy
- valory/ledger_api:1.0.0:bafybeif2c3jt4tim3zbfq5c2lds7bs6qj5gvj2obk3pzdk3uy6zk2ivo3e
skills:
- valory/abstract_abci:0.1.0:bafybeihovddle5vxf3axlph2kftigquk4u2wyhisg4fn4yxgmrin5kkwgq
- valory/abstract_round_abci:0.1.0:bafybeig5mcxjut2dk62ijcm7v6n56dvqhhsclsblizoyllapte34ftg6vi
- valory/test_abci:0.1.0:bafybeicvzekc55gvojl4vmgdmqznfk5oj4dkgim27tymlpldvb3l76juje
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - console
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/test_abci:0.1.0
  use_tendermint: true
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${P2P_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${P2P_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  - uri: ${P2P_URI:str:acn.staging.autonolas.tech:9006}
    public_key: ${P2P_PUBLIC_KEY:str:02e741c62d706e1dcf6986bf37fa74b98681bc32669623ac9ee6ff72488d4f59e8}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${P2P_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${P2P_PUBLIC_KEY:str:02e741c62d706e1dcf6986bf37fa74b98681bc32669623ac9ee6ff72488d4f59e8}
  save_path: .certs/acn_cosmos_9006.txt
is_abstract: true
