name: register_reset
author: valory
version: 0.1.0
agent: valory/register_reset:0.1.0:bafybeihd7ovp7myncsrwdzf4b65d7mmkt2esfrrpb7zvi2khds72qcwyxi
number_of_agents: 4
description: Test and debug tendermint reset mechanism.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiae4sog7e3hyjdujzp5qr2g3auobmqswqnaczh2zhlphuojnd2g6u
  abci_build/agent_keys/agent_0_private_key.yaml: bafybeihpmwbsanovqbpulie7gz5udx2wxetsr4kumilffsbgr67anget6a
  abci_build/agent_keys/agent_1_private_key.yaml: bafybeiafn2ujdjyx3ihamyokxdcokcv2wjmc7bw3mokfd2awnzabwm322e
  abci_build/agent_keys/agent_2_private_key.yaml: bafybeicw25r4fuksqat3csvkq7delzvwsjuhwcckn7e3z7bkgekscrnqzm
  abci_build/agent_keys/agent_3_private_key.yaml: bafybeiahzn2tl2pi5dnhfno5i6v2ouwzxxqu3vf5lhtdn4clkyw4jku5gq
  abci_build/build.yaml: bafybeicasw67wuwngj74ispmzwhrauuhwlyjgocls5rawrnv7g4ragcstm
  keys.json: bafybeiafloafha4cvayjd6cbfdeumgbxxun2loafyuyjessfzpekjxwwby
fingerprint_ignore_patterns: []
deployment: {}
dependencies: {}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${SERVICE_REGISTER_RESET_RPC:str:http://host.docker.internal:8545}
      chain_id: 31337
      poa_chain: false
      default_gas_price_strategy: eip1559
